### ISSUE TITLE
Data Structure

### ISSUE THREAD

**Issue by georgeedwards** [NativeScript/plugins#19]
For front-end/back-end collaboration, I think we should discuss the data we need to store/ share via API.

So far I need:

```
export declare class plugin {
    title: string;
    author: string;
    stars: number;
    description: string;
    ios: boolean;
    android: boolean;
    repo: string;
    readme: string;
}
```

But in Nina's wireframes, the plugin detail also includes:

- [x] Angular/NativeScript/Both

- [x] Keywords
- [ ] License
- [ ] Plugin Size

- [ ] Last (Day/Week/Month) downloads

- [ ] Contributors

- [ ] ~~Language / TypeScript version~~
- [ ] ~~GitHub issues~~
- [ ] ~~Demo URL~~
- [ ] ~~android version~~
- [ ] ~~iOS version~~

Which of the above would we like to include for our v1?

**Comment by georgeedwards** [comment]
Some Other thoughts -

1.  Does the ReadMe string have to be escaped? 
2. Is the plugin title always going to be the same as the npm name? i.e. cam I do `<h3>npm i {{Plugin.title }}</h3>`?

**Comment by NathanaelA** [comment]
1. I'd have to check. -- I believe they must be because I store them all in a JSON file right now...
2. I'd have to check.  :grinning:   --  but I believe they are the same.

**Comment by NathanaelA** [comment]
Some of that data won't be valid until v2, for example there won't be a demo url.  We can detect if a demo project exists in github; but since we aren't building anything we won't be able to detect if it works or to create a apk that they can download/run...   

- iOS & Android version is pointless imho.  We just need to know if the plugin supports iOS, and/or Android.  
- We also should probably track if the plugin is Angular only, NativeScript only or works on both sides of the fence.  
- GitHub issues a something I believe we decided not to track this.   The biggest issue with tracking this number is that some people (like me) use Git to list future enhancements and/or questions.   Showing this number might appear that there are actually open "issues" when the plugin is solid.

I also don't see a Category(?) or Tags(?) in your data; when you are dealing with >100 plugins it is much nicer to be able to drill down to it.   I really don't want to be scrolling through 300+ plugins to find one.  

@NathanWalker Should we do maybe tags or just assign categories like I did with NS.Rocks.   We can recommend that the category and/or tags be added to the authors package.json file so that we eliminate manually putting them in.   But right now, this process takes me 5 minutes a week to classify new plugins on NS.rocks.

**Comment by georgeedwards** [comment]
@NathanaelA I have updated the initial list to reflect your comments, re: Categories, that sounds great, I had asked on #18 (SideBar), but has assumed no comment meant no. How will these be generated? Will they be one of a preset number or will users be able to define their own? If predefined, what will they be?

As for tags, I have keywords, happy to rename it, but I suppose that is about the same thing?

**Comment by NathanaelA** [comment]
I also forgot we probably should have a tag /picture to specify if the plugin is commercial.   I know I sell several plugins and Telerik has at least one plugin so far that is commercial.
