### ISSUE TITLE
[@nativescript/geolocation] android: Remove background location permission

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/plugins#192]
Coming in April 2022 Google will require for developers to provide how do they use data and sensitive permissions: https://android-developers.googleblog.com/2021/10/launching-data-safety-in-play-console.html . Seems the background location permission is considered a sensitive one and you are **required** to provide written explanation and a video for what are you using this: https://support.google.com/googleplay/android-developer/answer/9799150?hl=en
Since the permission is automatically added by the geolocation plugin even if the app does not use background it will cause problems with apps in the Play Store. 

Can we do one of the following:
* Remove the `android.permission.ACCESS_BACKGROUND_LOCATION` from the manifest of the plugin and remove it from code that requests it. Add a section in the README that in case users that need this permission it should be manually added in the apps manifest file and requested from the app itself. 
* Provide somehow configuration options for users to remove the permission from their app in case it is not used. 
* Split background functions in a separate plugin

**Comment by bradmartin** [comment]
@PeterStaev  - removed all the permissions and documented on the README. Hopefully that fixes this and is better. Was on the fence about removing COARSE since it's the approximate one and shouldn't cause issues, but also maybe it helps for devs to learn a little about permissions on the platform so adding one permission could be a positive for educating new devs. Pros/cons both ways, but hopefully now the background isn't a blocker for those not needing it.
