### ISSUE TITLE
Notes from 10/14 Meeting

### ISSUE THREAD

**Issue by jlooper** [NativeScript/plugins#3]
Attendees: Rob Lauer, TJ Van Toll, Jen Looper, George Edwards, Nathan Walker on Skype

---

Plugins Marketplace Chat Agenda

Rob - kick off, here’s what we have, here’s what we want

George - talk about your work

Nathanael/Nathan - talk about N.rocks

plan of action
1. nail down the MVP
2. designs from Nina
3. next steps?

---

The problem: We have a disparate set of plugins currently listed as 'verified' on Telerik.com/plugins - there are for example too many Cordova plugins w/o structure, they are also hard to discover
- for Cordova plugins, we provided a curated set of plugins to put our name behind
- for NativeScript, it’s just a list, and not complete

Where we want to go: a community-led effort w/ Progress’s backing. Progress proposes:
- to provide guidance and nurturing and resources, but stay out of your way
- to provide transparency w/ an engaging experience to create a true hub for plugins

We would like to see:
- an MVP relatively soon :)
- we'd like to provide more guidance on plugin dev as well
- we'd like to drop the current verified marketplace

Current community proposals: 
- Nathan W and Nathanael A: use angular seed for plugins site (maybe advanced seed for desktop app)
- George E: ns-docs.herokuapp.com/docs

An architectural vision:
- web app with search box
- process scripts to help create plugin aggregation
- if server-side scripting is necessary we might consider firebase hosting or George's current Travis setup

Proposed work breakdown: 
Nathanael - automation
Nathan - ng2 seed
George - for design
Nina - functional prototype

We will need NIna's prototypes to begin but propose:
- A budget TBD
- Creation of Github repo (/nativescript/plugins) 
- Hosting of site as a Github pages site but linked to  nativescript.org, maybe with a plugin banner from homepage linked over to new hub

We prefer scripts to remain public
Proposal: 2 different folders, one for Travis project that takes angular 2 and builds it, the other for content

Next steps: 
Nina will provide design specs
Participants then estimate costs
Once we get these we can start a bi-weekly standup on Slack: join the TDE Slack channel in the #plugin-hub room

**Comment by NathanaelA** [comment]
Server side is required for several things:
1. To aggregate plugins from NPM/GIT (v1)
2. To check the actual githubs of each plugin (v1)
3. To pull down the githubs of each plugin (v1)
4. To Build the plugin app (v1)
5. To run the demos of each plugin (v2)
6. To run unit tests of each plugin (v2)
--- 
I don't think Travis is a good idea for this.  Here is the reasoning.   The aggregating of plugins is fairly simple; and can be done on travis -- but pulling the data from the rest of everything (ie 2-6) requires us to run both a iOS and Android emulator to verify that everything still works.  This means that the environment has to be pre-setup to have XCode+support, Android+support and all the NS stuff all ready setup and working.   Some of this can be automated; but then if we have to automate installing this each time; it means the time to test is going to be longer.   In addition when a new version of NS is released we have to run this against all 300ish (and growing) plugins again using the new version of NS, to verify compliance.

So daily you have maybe a several dozen runs (for each published plugin updated that day), and every 6 weeks you have 300+ runs.   This is not what travis is built for, and if you go for a license that allows you to do this -- you might as well be paying for your own dedicated server (its cheaper than travis).    

Optimally we need access to at least one Mac VM / Dedicated Mac server (have to run iOS simulator & ios unit tests ) and then the same box can also run Android tests.    

Several data points we need to be able to build the app (even if we don't run it) to be able to get the info.  So planning for this up front is way better than doing things one way and then having to scrap all that work to do something different when we switch to v2.  It would be better to progressively add v2 features as we have the additional resources for it.

---

Once we build the data -- there is no reason we can't git push that back to the "plugin" repo so that the site doesn't need server side processing.   But the actual collecting of the data needs server side support.  

---

However, what is the idea for how to track user login/ratings per plugin, this is done a lot easier with server side support.   So does this mean maybe it should just go back to being a dedicated server like NS.rocks is now...  ;-)

**Comment by georgeedwards** [comment]
My proposal also has server-side support, hosted on Heroku. However, I also have an externally managed mLab MongoDB instance and use Auth0 (as described on #6 ). This removes those aspects from what we have to worry about. 

I think a reasonably strong consensus (and one I really support) is that whatever front end/backend should be built using NativeScript compatible technologies, e.g. TypeScript and Angular2.

With Angular2, you have to have some build chain to compile and bundle, otherwise, the performance is not good. That is what I was using Travis for - not the plugin aggregation etc. I did that in my nodeJS backend.

These are all considerations as whether the Angular2-seed is the right approach. I started using it, but then ended up moving to having a `client` and `server` directory.

**Comment by NathanaelA** [comment]
Ok, I have a couple comments.  

First of all George, I am very strongly opinionated about some things, since I've lived through the aftermath of poor management decisions which almost always occurred when they choose to ignore my advice.  :-)    I've been doing DevOps for over 20 years; so I have a very wide range of experiences running both small sites and really (really) large sites in a wide number of technologies.     I've built the plugins site over 8 months ago, and maintained the list for several months before that.   (And add the 25+ plugins I've written).  So plugins has been my baby for a really long time.  Nathan and I have already discussed upgrades long before Telerik got involved; so we are trying to figure out how everything fits into the vision.    

First thing you need to do is plan for above the normal case for where you are attempting to be at.   We want to be at a point (v2) to scan all 300+ plugins on each tns release to make sure they still function.   This is the use case we need to plan for _now_.   If you don't take in account where we are going, you end up scrapping a lot of decisions that you made earlier.   For example; using Amazon/Heroku/Progress for v1 would work fine.  But Heroku, Amazon (or even Progress's) gets really expensive when you start using any _real_ amount of processing power or disk space -- which will occur when Building every single plugin (300+) on every release will do.  In addition they also get very expensive when you start getting a lot of traffic (which pulling all 300 plugins from github will do), let alone the traffic we hope to get from users (and connections to mtab under your idea).  So in my mind those are non-starters; they DO NOT let us grow to v2 easily (or I should say in-expensively).  

I currently pay a grand total of $99 for a 2TB (of Disk), 8 Core (3.3ghz), 8GB ram, and gigabit ethernet, peered in a top ranking facility.   I can run whatever I want on the machine, and ALL connections from Front-end to backend /databases are all local meaning the site can be exceptionally fast.   Even while building the NativeScript Masters (Java, C++) daily, the machine has no speed issues.    I already pay for this machine (and several others), it is what runs everything that I do related to NativeScript (and other of my own projects).    I have no issues leaving NS.Rocks on this machine as it already is.   If we find that the plugin site when doing 300 plugins is causing issues for other of my customers, then we will have some hard data to determine what type of machine(s) we will need and we can the evaluate how to host it.   But in my mind doing DevOps for many (many) years; amazon/Heroku are actually bad solutions to our end result problem that we have to solve.

As for using TypeScript/Angular 2 -- the ONLY reason I'm even considering using this on the front end is because Nathan Walker is awesome at it, I want to learn it (ng2), and ng2 now offers server side rendering support.   I can live with ng2 if we use tree shaking and server side rendering to eliminate the majority of the issues in ng2 that I see.    If either of those were not true, I would not be very agreeable to ng2.  It is a huge framework for such a small site.  (five basic pages: Index, Plugin list, author list, plugin/author details).

   The current Website with Sorting and filtering and all graphics and ALL DATA (which the data is the largest part) is only 40k, without any compression, if I used compression (i.e. pre-gzip'd things) the size is closer to 20k.    NG2 there is NO way to even get the footprint even remotely close to that small.  I happen to like blazing FAST sites.  I don't like slow sites; and I actually for the most part really hate most client side only rendering sites as they are typically terribly slow in comparison.   So for me a client side rendered site is mostly a non-starter.    From the get-go, the server needs to be setup to do server side rendering of the site.  We want this site to be as close to as fast as the existing site.

I don't think we need to use the NativeScript-NG2 seed.  I think a desktop site is the primary goal.  I rarely ever go to nsrocks on a phone, because when I need a plugin I'm on my development machine.  ;-)   Thats not to say we don't support phones, it is just that we need to target the largest part of the people perusing the site, which I believe is desktop machines.

The current processing backend on nsrocks is pure JavaScript (node).  The Backend for what renders the site pages is actually php.   I have NO issues personally using whatever is the best tool for the job.  At the time I had a vast library of php sites; so dropping some code into a php shell I wrote was quick and simple.  :-)

I'll be frank, I am opposed to using TS for the backend processing.   TS does NOT offer me anything at all, and in fact just slows development down (drastically) in my case.   Using a current version of node, you get all the ES6 & some ES7 capabilities out of the box which eliminates pretty much anything positive that TS could offer me.    

For the front end; since Nathan is in charge, he is totally free to use TS, I have no issues if he find TS is the most productive for him.   I'll follow his lead (using TS) on any help that I provide him on the front end.

**Comment by jlooper** [comment]
One thing I do want to mention is that using Modulus would allow you to scale up and back as you spin up servos (thus their new name, Xervo). They are a Progress company so I'm pretty sure we could get it for free if we tell them what's up up front. In terms of enterprise-level node hosting, they would be a solid bet.

**Comment by NathanaelA** [comment]
If we could get it for free; I am not at all opposed to it.  Free is always better than $99.   ;-)   

However do you realize they sub-contract out the boxes actually to AWS, Joyent, etc, which means even though the NativeScript team isn't paying the costs; Progress the company is; because it cost them money to run the machine on the third party vendor.

**Comment by jlooper** [comment]
Yes, of course! :) but better us paying than you, amirite?

**Comment by georgeedwards** [comment]
OK re: technology, I have no major problem with JS, I am more rooting for nodeJS. On the infrastructure front, I just think it needs to be accessible and transparent for future contributors.

**Comment by NathanWalker** [comment]
I don't know much about Modulus, but could someone set that up for @NathanaelA and I to begin experimenting with?

**Comment by jlooper** [comment]
@NathanWalker et al I set up a Modulus.io account for us to tinker with. If you decide to use it I'll talk to sales about the costs. The authentication is the same as what I just did for Auth0.

**Comment by NathanWalker** [comment]
Excellent, thank you @jlooper  👍
