### ISSUE TITLE
Google signin Android error

### ISSUE THREAD

**Issue by realtica** [NativeScript/plugins#397]
NS: 8.4.0
Angular: 15.0.4

  ```
import { GoogleSignin } from "@nativescript/google-signin";

ngOnInit(): void {
    // Use the "ngOnInit" handler to initialize data for the view.
    GoogleSignin.configure({
      scopes: [
        "https://www.googleapis.com/auth/userinfo.email"
      ]
    });
  }
```

`JS: ERROR Error: Uncaught (in promise): Error: String resource ID #0x0`

**Comment by meganedesigns** [comment]
Which version of `@nativescript/google-signin` are you using?

**Comment by CatchABus** [comment]
> NS: 8.4.0 Angular: 15.0.4
> 
> ```
> import { GoogleSignin } from "@nativescript/google-signin";
> 
> ngOnInit(): void {
>   // Use the "ngOnInit" handler to initialize data for the view.
>   GoogleSignin.configure({
>     scopes: [
>       "https://www.googleapis.com/auth/userinfo.email"
>     ]
>   });
> }
> ```
> 
> `JS: ERROR Error: Uncaught (in promise): Error: String resource ID #0x0`

This error might be due to missing `default_web_client_id` resource in your app resources.
This is usually generated automatically (see https://developers.google.com/android/guides/google-services-plugin) but it doesn't seem to do in your case.

EDITED: 
You can avoid all this if you include `clientId` in your configure options.
```js
 GoogleSignin.configure({
     clientId: "my client id",
     scopes: [
       "https://www.googleapis.com/auth/userinfo.email"
     ]
 });
```
Otherwise, this should help setup your firebase project authentication properly: https://chetan-garg36.medium.com/resolve-default-web-client-id-please-a37508e3f88b
