### ISSUE TITLE
Mobile layout alignment issue - chrome

### ISSUE THREAD

**Issue by bradmartin** [NativeScript/plugins#60]
![screenshot_20170204-173218](https://cloud.githubusercontent.com/assets/6006148/22622453/3fa13f5c-eb00-11e6-8206-392d15e04e87.png)
![screenshot_20170204-173148](https://cloud.githubusercontent.com/assets/6006148/22622456/50e0ae92-eb00-11e6-9ab2-282be5db7f15.png)
![screenshot_20170204-173209](https://cloud.githubusercontent.com/assets/6006148/22622457/513c8b54-eb00-11e6-9d8e-3905730817f9.png)

I can circle back around to this later and inspect the layout for more info. Just found this on my phone and didn't want to forget logging it.

**Comment by NathanWalker** [comment]
@bradmartin i added some media query styles to help - more that can be done, but refresh the site on mobile to ensure you get latest deploy and lemme know if any better.
For now, just hiding the sidebar on mobile and upper right nav, since mobile is likely just good for browsing at leisure rather than actively using the info since you can't install anything unless you're on desktop.

**Comment by bradmartin** [comment]
Much better 👍

**Comment by georgeedwards** [comment]
@bradmartin should I close this, or do you want some more work done on this?

**Comment by bradmartin** [comment]
All good for now 😄, always work to do but this was a great quick fix.
