### ISSUE TITLE
Setup site and backend setup on Modulus

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/plugins#9]

**Comment by NathanaelA** [comment]
@jlooper - can you check with the modulus team to see if we can get a Macintosh VM?   If we want to build and test iOS plugins we have to have something to build all plugins on iOS also...    Otherwise Modulus is imho a non-starter because we can't use it for our actual build part of the goal...

**Comment by NathanaelA** [comment]
To clarify we technically can use modulus to host the actual website; but then we have to have a separate build server, rather than one server that just handles everything initially.   My preference is one server total to keep costs done; but if you prefer to do multiple servers, that is also an option...

**Comment by jlooper** [comment]
I see the issue. I've opened a req with the team. It may well be it will not provide the server-side functionality that we need. I'll let you know when I hear back.
