### ISSUE TITLE
[@nativescript/animated-circle] An uncaught Exception occurred on "main" thread. Calling js method onCreateView failed. Error: Expected 1 or 4 constructor parameters.

### ISSUE THREAD

**Issue by omprakashgupta-dev** [NativeScript/plugins#92]
I have created a new project(angular) based on nativescript 7.2. I have added the plugin : _@nativescript/animated-circle._ While running the app getting the error: _Expected 1 or 4 constructor parameters._

**app.module.ts**
```ts
import { NativeScriptAnimatedCircleModule } from '@nativescript/animated-circle/angular';

@NgModule({
    bootstrap: [
        AppComponent
    ],
    imports: [
        NativeScriptModule,
        AppRoutingModule,
        NativeScriptFormsModule,
        NativeScriptHttpClientModule,
        NativeScriptAnimatedCircleModule,
    ],
    declarations: [ // User Controls
        AppComponent,
        ...navigatableComponents,
    ],
    providers: [ // Equivalent to autofac register builder.
    ],
    schemas: [
        NO_ERRORS_SCHEMA
    ]
})
export class AppModule { }
```

**Test.component.html**
```html
<StackLayout >
  <AnimatedCircle row="0" 
    col="0" 
    backgroundColor="transparent" 
    width="200" 
    height="200" 
    startAngle="0" 
    animationDuration="1000" 
    animated="true" 
    animateFrom="0" 
    rimColor="#fff000" 
    barColor="#ff4081" 
    rimWidth="25" 
    progress="50"
    text="" 
    textSize="22" 
    textColor="#336699"></AnimatedCircle>
</StackLayout>
```

**Comment by rigor789** [comment]
Can you please post the full stack-trace of the error to help us identify where it is being thrown?

**Comment by OPADA-Eng** [comment]
JS: Binding: Binding error while setting property barColor of AnimatedCircle(242)@pages/Dashboard/salesMgr/salesMgr-page.xml:37:25;: Error: Expected 1 or 4 constructor parameters.
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onCreateViewHolder failed
System.err: Error: Cannot convert object to F at index 0
System.err: 
System.err: StackTrace:
System.err: initNativeView(file: node_modules/@nativescript/animated-circle/index.android.js:32:0)
System.err:     at setNativeView(file: node_modules/@nativescript/core/ui/core/view-base/index.js:582:0)
System.err:     at _setupUI(file: node_modules/@nativescript/core/ui/core/view-base/index.js:560:0)
System.err:     at (file: node_modules/@nativescript/core/ui/core/view-base/index.js:567:0)
System.err:     at eachChildView(file: node_modules/@nativescript/core/ui/layouts/layout-base-common.js:101:0)
System.err:     at eachChild(file: node_modules/@nativescript/core/ui/core/view/view-common.js:700:0)
System.err:     at _setupUI(file: node_modules/@nativescript/core/ui/core/view-base/index.js:566:0)
System.err:     at (file: node_modules/@nativescript/core/ui/core/view-base/index.js:567:0)
System.err:     at eachChildView(file: node_modules/@nativescript/core/ui/layouts/layout-base-common.js:101:0)
System.err:     at eachChild(file: node_modules/@nativescript/core/ui/core/view/view-common.js:700:0)
System.err:     at _setupUI(file: node_modules/@nativescript/core/ui/core/view-base/index.js:566:0)
System.err:     at _addViewCore(file: node_modules/@nativescript/core/ui/core/view-base/index.js:429:0)
System.err:     at _addView(file: node_modules/@nativescript/core/ui/core/view-base/index.js:418:0)
System.err:     at ListViewAdapter.onCreateViewHolder(file: node_modules/nativescript-ui-listview/ui-listview.android.js:108:0)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1175)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1153)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1149)
System.err:     at com.tns.gen.com.telerik.widget.list.ListViewAdapter_vendor_121804_28_ListViewAdapter.onCreateViewHolder(ListViewAdapter_vendor_121804_28_ListViewAdapter.java:41)
System.err:     at com.telerik.widget.list.ListViewWrapperAdapter.onCreateViewHolder(ListViewWrapperAdapter.java:468)
System.err:     at com.telerik.widget.list.ListViewWrapperAdapter.onCreateViewHolder(ListViewWrapperAdapter.java:20)
System.err:     at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7078)
System.err:     at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6235)
System.err:     at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
System.err:     at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
System.err:     at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
System.err:     at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
System.err:     at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
System.err:     at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
System.err:     at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
System.err:     at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
System.err:     at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
System.err:     at com.telerik.widget.list.RadListView.onLayout(RadListView.java:600)
System.err:     at android.view.View.layout(View.java:22844)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6389)
System.err:     at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
System.err:     at android.view.View.layout(View.java:22844)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6389)
System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
System.err:     at android.view.View.layout(View.java:22844)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6389)
System.err:     at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:354)
System.err:     at android.view.View.layout(View.java:22844)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6389)
System.err:     at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:354)
System.err:     at android.view.View.layout(View.java:22844)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6389)
System.err:     at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     at org.nativescript.widgets.ContentLayout.onLayout(ContentLayout.java:73)
System.err:     at android.view.View.layout(View.java:22844)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6389)
System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
System.err:     at android.view.View.layout(View.java:22844)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6389)
System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
System.err:     at android.view.View.layout(View.java:22844)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6389)
System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
System.err:     at android.view.View.layout(View.java:22844)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6389)
System.err:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
System.err:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
System.err:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
System.err:     at android.view.View.layout(View.java:22844)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6389)
System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
System.err:     at android.view.View.layout(View.java:22844)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6389)
System.err:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
System.err:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
System.err:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
System.err:     at android.view.View.layout(View.java:22844)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6389)
System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
System.err:     at com.android.internal.policy.DecorView.onLayout(DecorView.java:784)
System.err:     at android.view.View.layout(View.java:22844)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6389)
System.err:     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3470)
System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2938)
System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1952)
System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8171)
System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:796)
System.err:     at android.view.Choreographer.doFrame(Choreographer.java:731)
System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
System.err:     at android.os.Handler.handleCallback(Handler.java:938)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
System.err:     at android.os.Looper.loop(Looper.java:223)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7656)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

This happens when I set the bar color to a bindedContext property for the attribute: "barColor"

**Comment by Alidar40** [comment]
Hey, I had this error and I found the solution.

The problem is with `fillColor`, `spinBarColor` and `rimColor` properties:
In `index.android.ts` in `updateAnimatedCircle()` method new Color objects are created (see lines 291, 294, 314)

This: `new Color(this.rimColor).argb` causes the error. Using just `this.rimColor.argb` is enough.

Now, to make it compile one should define this three properties in AnimatedCircle tag

I didn't find any mention of `spinBarColor` in the docs.

Also setters of this three properties are strange:
For example, `set barColor` 1) uses types 2) first checks the value and only then assigns it.
While `set fillColor`, `set spinBarColor` and `set rimColor` 1) use `any` 2) check the value after assignment.

nativescript 7.2
animated-circle 1.1.6
Top of the stack-trace:
> System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onCreateView failed
System.err: Error: Expected 1 or 4 constructor parameters.
System.err: 
System.err: StackTrace:
System.err: ZoneAwareError(file: node_modules/@nativescript/zone-js/zone-nativescript.js:1298:0)
System.err: 	at Color(file: node_modules/@nativescript/core/color/color-common.js:43:0)
System.err: 	at Color(file: node_modules/@nativescript/core/color/index.android.js:2:7)
System.err: 	at updateAnimatedCircle(file: node_modules/@nativescript/animated-circle/index.android.js:272:0)
System.err: 	at initNativeView(file: node_modules/@nativescript/animated-circle/index.android.js:42:0)
System.err: 	at setNativeView(file: node_modules/@nativescript/core/ui/core/view-base/index.js:582:0)
System.err: 	at _setupUI(file: node_modules/@nativescript/core/ui/core/view-base/index.js:560:0)
System.err: 	at (file: node_modules/@nativescript/core/ui/core/view-base/index.js:567:0)
System.err: 	at eachChildView(file: node_modules/@nativescript/core/ui/layouts/layout-base-common.js:101:0)
...
...

**Comment by asikalove** [comment]
I've hit the same problem. I'll appreciate getting any any solution @NathanWalker

**Comment by BrothersWar** [comment]
same problem

**Comment by asikalove** [comment]
@Alidar40 thanks. that's help with error. But, do you have issue with text size and **bar/rim color** on Android? 

"@nativescript/animated-circle": "^1.1.6",
"nativesript": 7.2.0
"typescript": "4.1.5"

```
<AnimatedCircle
           [barColor]="barColor"
           [progress]="progress"
           [textColor]="barColor"
           [textSize]="textSize"
           backgroundColor="transparent"
           height="80"
           rimColor="#c4c4c4"
           rimWidth="4"
           rowSpan="2"
           text="{{ progress }}%"
            width="80"
            ></AnimatedCircle>
```
This code doesn't show me correct rim color and font size.
Text should be purple, also remaining bar is not grey
![Screenshot at May 10 13-06-32](https://user-images.githubusercontent.com/70281651/117644709-715a0a80-b192-11eb-93b0-61fa6e368c1e.png) 
Do you have any idea? Thanks!

**Comment by OPADA-Eng** [comment]
Any updates to get this updated and fixed in a new release?
@NathanWalker

**Comment by neotrouz** [comment]
I've create PR to fix this https://github.com/NativeScript/plugins/pull/169 @NathanWalker

**Comment by NathanWalker** [comment]
Published with 1.1.7 thank you @neotrouz

**Comment by OPADA-Eng** [comment]
But the issue still exists in 1.1.7 specifically in line 270:
`this.android.setSpinBarColor(new Color(this.spinBarColor).argb);`
the same error occur.
```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onCreateViewHolder failed
System.err: Error: Expected 1 or 4 constructor parameters.
System.err: 
System.err: StackTrace:
System.err: Color(file: node_modules/@nativescript/core/color/color-common.js:38:0)
System.err:     at Color(file: node_modules/@nativescript/core/color/index.android.js:2:7)
System.err:     at updateAnimatedCircle(file: node_modules/@nativescript/animated-circle/index.android.js:270:0)
```

**Comment by neotrouz** [comment]
@OPADA-Eng Can you share your animated-circle config options? So I can do some test

**Comment by OPADA-Eng** [comment]
`                                <ui:AnimatedCircle verticalAlignment="center" class="m-5" backgroundColor="transparent" width="90" height="90" animated="true" animateFrom="0" rimColor="#ababab" barColor="#ababab" fillColor="#aaaaaa" clockwise="true" rimWidth="5" progress="{{ percentage }}" text="{{ percentage+'%' }}" textSize="18" textColor="#000000" />
`

**Comment by neotrouz** [comment]
![image](https://user-images.githubusercontent.com/8170621/133879947-1ac51ce0-4df2-4815-bd7e-31f04ea20943.png)
Work well for me @OPADA-Eng

**Comment by OPADA-Eng** [comment]
```
core version:   "@nativescript/core": "^7.3.0",
plugin version: "@nativescript/animated-circle": "^1.1.7",
"devDependencies": {
    "@nativescript/android": "8.0.0",
    "@nativescript/ios": "8.0.0",
    "@nativescript/types": "7.3.0",
    "@types/lodash": "^4.14.168",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "lazy": "1.0.11",
    "nativescript-worker-loader": "^0.12.1",
    "typescript": "4.2.3"
  },
ns --version
8.0.2
```
